### ISSUE TITLE
Use `rm -r` to see errors

### ISSUE THREAD

**Issue by isaachier** [pgadige/katacoda-scenarios#1]
Avoid using `rm -rf` if you want it to fail on error. Use `rm -r` instead. I'm guess the removal fails, causing `git clone` to fail at some point down the line.

https://github.com/pgadige/katacoda-scenarios/blob/379f6f3a554502c4c65837dd24e7993ae3906fb8/opentracing-python-tutorial/set-env.sh#L1

**Comment by pgadige** [comment]
Thank you for your feedback, @isaachier ! I truly appreciate it. I made the necessary change and committed it to the repo.
